---
title: "p8105_hw5"
author: "Chu YU"
date: "2018-11-4"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw() + theme(legend.position = "right"))
```

#problem 1

### data cleaning
```{r}
## import data and clean data
sdy_df = 
    tibble(file_name = list.files(path = "./data/")) %>% 
    mutate(subject_df = map(str_c("./data/", file_name), ~read_csv(.x))) %>% 
    unnest() %>%
    separate(file_name, into = c("group", "id"), sep = "_") %>% 
    gather(key = week, value = value, week_1:week_8) %>% 
    mutate(id = factor(str_replace(id, ".csv", "")),
        week = as.numeric(str_replace(week, "week_", "")))

```

### making plots about the study
```{r}
##spaghetti plot 
sdy_df %>%
  ggplot(aes(x = week, y = value, color = group)) +
  geom_line(aes(group = id)) +
  geom_smooth(se = F) +
  facet_grid(.~ group) +
  labs(
    title = "spaghetti plot of observations on each subject over time",
    x = "week",
    y = "study value"
  ) 
  
  
```

# problem 2
### import data
```{r}
## import the data
homicide_df = read.csv("./homicide-data.csv") 

## new variable
homicide_num = homicide_df %>%
  mutate(city_state = str_c(city,",", state)) %>%
  group_by(city_state) %>%
  summarise(total_num = n(),
            unsolved_num = sum(disposition %in% c("Closed without arrest", "Open/No arrest")))
 
```

### For the city of Baltimore, MD
```{r}
## filer the baltimore MD
bd_df = homicide_num %>%
  filter(city_state == "Baltimore,MD")

## prop.test
bd_prop = prop.test(bd_df$unsolved_num, bd_df$total_num)

## tidy
broom::tidy(bd_prop) %>%
  select(estimate, conf.low, conf.high) %>%
  knitr::kable(caption = "stats table of Baltimore MD", digits = 4)
```


### for each of the cities in dataset
```{r}
homicide_prop = homicide_num %>%
  mutate(prop 
         = map2(.x = unsolved_num, .y = total_num, ~broom::tidy(prop.test(.x,.y)))) %>%
  unnest() %>%
  select(city_state,estimate, conf.low, conf.high) 

```

### creating a plot
```{r}
homicide_prop %>%
  ggplot(aes(y = estimate,x = reorder(city_state, estimate))) + 
  geom_point() +
  geom_errorbar(aes(x = city_state, ymin = conf.low, ymax = conf.high)) +
  labs(
    title = "scatterplot of the estimates and CIs for each city",
    x = "city and state name",
    y = "proportion of unsolved crimes "
  ) +
   theme(axis.text.x = element_text(angle = 60, hjust = 1))
  
  
```

